services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./images:/images
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - db
  db:
    image: postgres:17.1-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: ${PSQL_DATABASE}
